import os
from datetime import datetime
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.units import inch


def create_pdf(report, filename="reports/research_report.pdf"):
    """
    Creates a professional PDF report.
    """

    os.makedirs("reports", exist_ok=True)

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    # Title Style
    title_style = styles["Title"]
    title_style.alignment = TA_CENTER
    title_style.textColor = HexColor("#003366")

    # Heading Style
    heading_style = styles["Heading2"]
    heading_style.textColor = HexColor("#0B5394")

    # Body Style
    body_style = styles["BodyText"]
    body_style.leading = 18

    story = []

    # Title
    story.append(Paragraph("Autonomous Research Agent", title_style))
    story.append(Spacer(1, 0.15 * inch))

    # Generated Date
    generated_time = datetime.now().strftime("%d %B %Y, %I:%M %p")
    story.append(
        Paragraph(
            f"<b>Generated On:</b> {generated_time}",
            body_style
        )
    )

    story.append(Spacer(1, 0.25 * inch))

    # Report Content
    for line in report.split("\n"):

        line = line.strip()

        if not line:
            continue

        if (
            "Research Report" in line
            or line.startswith("Key Points")
            or line.startswith("Important Findings")
            or line.startswith("References")
            or line.startswith("Actionable Insights")
        ):

            story.append(Paragraph(line, heading_style))
            story.append(Spacer(1, 0.10 * inch))

        else:
            story.append(Paragraph(line, body_style))

    story.append(Spacer(1, 0.30 * inch))

    story.append(
        Paragraph(
            "<font color='grey'><i>Generated by Autonomous Research Agent</i></font>",
            body_style
        )
    )

    doc.build(story)

    return filename